{
 "title": "Havoc Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "World Map of Exploited Hosts",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "target_ip.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "geoip.location",
       "id": "4",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "field": "target_ip.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "task_type=metasploit AND outcome=success",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful Metasploit Exploits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "instruct_command=execute_exploit AND outcome=success",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 } },
  {
   "title": "Metasploit Targets",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "target_ip.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "task_type=metasploit",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Metasploit Commands",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instruct_command.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "outcome.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "task_type=metasploit",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Metasploit Exploits",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "metasploit_exploit.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "task_type=metasploit",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Metasploit payloads",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "task_response.payload_module.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "task_type=metasploit",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NMAP Targets",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "target_ip.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "task_type=nmap",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NMAP Protocol / Port",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ip_protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "target_port",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "task_type=nmap",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NMAP Results",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 30 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "task_type=nmap",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}